services:
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./_infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./_infrastructure/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./_infrastructure/grafana/provisioning.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./_infrastructure/grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana-storage:
