# Generated by Django 5.1.7 on 2025-03-28 18:13

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('background_color', colorfield.fields.ColorField(default='#F0F0F0', image_field=None, max_length=25, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#FF5733', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('hamburger', 'Hamburger'), ('top_bar', 'Top Bar'), ('side_menu', 'Side Menu')], default='top_bar', max_length=255)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('email_link', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_link', models.URLField(blank=True, null=True)),
                ('icon_animation', models.CharField(choices=[('none', 'None'), ('bounce', 'Bounce'), ('spin', 'Spin')], default='none', max_length=255)),
                ('link_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('link_color_on_hover', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSectionBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.block')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('background_style', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('paralax', 'Paralax')], default='solid', max_length=255)),
                ('blog_style', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('carousel', 'Carousel')], default='grid', max_length=255)),
                ('blog_page_style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal')], default='modern', max_length=255)),
            ],
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.block')),
                ('style', models.CharField(choices=[('minimal', 'Minimal'), ('modern', 'Modern'), ('bold', 'Bold'), ('overlay_text', 'Overlay on Image'), ('split_layout', 'Split Layout')], default='minimal', max_length=255)),
                ('background_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('image', models.ImageField(upload_to='header_images/')),
                ('header', models.CharField(max_length=255)),
                ('header_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('header_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('subheading_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('subheading_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_link', models.URLField()),
                ('button_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
            ],
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='ProjectsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.block')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('background_style', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('paralax', 'Paralax')], default='solid', max_length=255)),
                ('project_style', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('carousel', 'Carousel')], default='grid', max_length=255)),
            ],
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='core.navigation')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('html_file', models.FileField(upload_to='blog_files/')),
                ('blog_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.blogsectionblock')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('link', models.URLField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('projects_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='core.projectsblock')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.colorscheme')),
                ('navigation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.navigation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_section_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.blogsectionblock')),
                ('header_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.headerblock')),
                ('projects_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projectsblock')),
            ],
        ),
    ]
