# Generated by Django 5.1.7 on 2025-03-30 14:24

from django.db import migrations, models
from django.utils.text import slugify

def populate_slug(apps, schema_editor):
    BlogPost = apps.get_model('core', 'BlogPost')
    for post in BlogPost.objects.all():
        post.slug = slugify(post.title)
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_headerblock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, null=True),
        ),
        migrations.RunPython(populate_slug),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
