# Generated by Django 5.1.7 on 2025-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blogpost_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='slug',
            field=models.SlugField(default='fill-this-in', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogsectionblock',
            name='blog_style',
            field=models.CharField(choices=[('grid', 'Grid'), ('rows', 'Rows'), ('minimalist', 'Minimalist'), ('carousel', 'Carousel')], default='grid', max_length=255),
        ),
    ]
