# Generated by Django 5.1.7 on 2025-04-14 17:59

from django.db import migrations, models
import uuid

def generate_unique_slug(index):
    return f"slug-{index}-{str(uuid.uuid4())[:8]}"  # Incorporates index for uniqueness

def set_unique_slugs(apps, schema_editor):
    ProjectItem = apps.get_model('core', 'ProjectItem')
    for index, project_item in enumerate(ProjectItem.objects.all()):
        project_item.slug = generate_unique_slug(index)
        project_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blogpost_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ProjectItem',
            name='slug',
            field=models.SlugField(
                max_length=255,
                default='temporary-slug',  # Non-unique default
            ),
        ),
        migrations.RunPython(
            code=set_unique_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='ProjectItem',
            name='slug',
            field=models.SlugField(
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='BlogSectionBlock',
            name='blog_style',
            field=models.CharField(choices=[('grid', 'Grid'), ('rows', 'Rows'), ('minimalist', 'Minimalist'), ('carousel', 'Carousel')], default='grid', max_length=255),
        ),
    ]