# Generated by Django 5.1.7 on 2025-04-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectitem_slug_alter_blogsectionblock_blog_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='blurb',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
