# Generated by Django 5.1.7 on 2025-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectitem_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(default=5),
        ),
    ]
