# Generated by Django 5.1.7 on 2025-08-07 16:37

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_me_images/')),
                ('background_color_override', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_me_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aboutmeblock'),
        ),
    ]
