- name: Get repository url using aws cli
  shell: aws ecr describe-repositories --repository-names portfolio-app --region us-east-1 --query 'repositories[0].repositoryUri' --output text
  register: ecr_repository

- name: Login to ECR
  shell: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{ ecr_repository.stdout }}

- name: Pull latest image from ECR
  shell: docker pull {{ ecr_repository.stdout }}:latest

- name: Run Django container
  docker_container:
    name: django
    image: "{{ ecr_repository.stdout }}:latest"
    state: started
    restart_policy: always
    network_mode: host
    pull: yes
    env:
      CLOUD: "True"
- name: Run Migrations
  command: /bin/bash -c "docker exec django python manage.py migrate"
