---
- name: Deploy Nginx with TLS and Reverse Proxy to Docker
  hosts: portfolio
  become: true

  vars:
    domain: "api.jonathanmath.com"

  tasks:
    - name: Install required packages
      apt:
        name:
          - nginx
          - docker.io
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: Create temporary Nginx config for HTTP
      copy:
        dest: "/etc/nginx/sites-available/{{ domain }}"
        content: |
          server {
              listen 80;
              server_name api.jonathanmath.com;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }

      notify: Restart Nginx
    - name: Enable Nginx site
      file:
        src: "/etc/nginx/sites-available/{{ domain }}"
        dest: "/etc/nginx/sites-enabled/{{ domain }}"
        state: link
      notify: Restart Nginx

    - name: Stop Nginx before getting a certificate
      systemd:
        name: nginx
        state: stopped

    - name: Create Nginx config for TLS reverse proxy to Docker container
      copy:
        dest: "/etc/nginx/sites-available/{{ domain }}"
        content: |
          server {
              listen 80;
              server_name {{ domain }};
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name {{ domain }};

              ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
              ssl_trusted_certificate /etc/letsencrypt/live/{{ domain }}/chain.pem;

              location / {
                  proxy_pass http://127.0.0.1:8080; # Docker container on port 8080
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Restart Nginx

    # - name: Ensure Docker container is running
    #   docker_container:
    #     name: "{{ container_name }}"
    #     image: "{{ container_image }}"
    #     state: started
    #     ports:
    #       - "80:80"

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
