---
- name: Configure SSL and Nginx for Portfolio
  hosts: portfolio
  become: yes

  vars:
    domain_name: "api.{{ lookup('env', 'TF_VAR_domain_name') }}.{{ lookup('env', 'TF_VAR_tld') }}"
    email: "{{ lookup('env', 'TF_VAR_email') }}"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Obtain SSL Certificate
      command: >
        certbot certonly --nginx --non-interactive --agree-tos
        -m {{ email }} -d {{ domain_name }}
      register: certbot_result
      changed_when: "'Congratulations' in certbot_result.stdout"

    - name: Create nginx configuration
      copy:
        dest: /etc/nginx/sites-available/portfolio
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name {{ domain_name }};

              ssl_certificate /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;

              client_max_body_size 2M;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable site and reload nginx
      shell: |
        ln -sf /etc/nginx/sites-available/portfolio /etc/nginx/sites-enabled/portfolio
        rm -f /etc/nginx/sites-enabled/default || true
        nginx -t
        systemctl reload nginx

    - name: Setup auto-renewal cron
      cron:
        name: "Auto-renew Let's Encrypt certificate"
        job: "certbot renew --quiet && systemctl reload nginx"
        minute: 0
        hour: 0
