name: Build Django app and push to to AWS ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471528030347:role/github-runner-role
          aws-region: us-east-1
      - name: Retrieve ECR URI from Secret
        run: echo "ECR_URI=${{ secrets.ECR_URI }}" >> $GITHUB_ENV
      - name: Build image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_URI }}
          docker build --file _infrastructure/docker/Dockerfile -t portfolio-app .
      - name: Push image to ECR
        run: |
          docker tag portfolio-app:latest ${{ env.ECR_URI }}:latest
          docker push ${{ env.ECR_URI }}:latest
