name: Build Django app and push to AWS ECR with versioning

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/GitHubRunnerRole
          aws-region: us-east-1

      - name: Get Git Commit Hash
        id: git-info
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
          docker build --file _infrastructure/docker/Dockerfile -t portfolio-app:${{ env.COMMIT_HASH }} -t portfolio-app:latest .
      - name: Push image to ECR
        run: |
          docker tag portfolio-app:${{ env.COMMIT_HASH }} ${{ secrets.ECR_URI }}:${{ env.COMMIT_HASH }}
          docker tag portfolio-app:latest ${{ secrets.ECR_URI }}:latest
          docker push ${{ secrets.ECR_URI }}:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.ECR_URI }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance, pull latest image, and rebuild docker container with latest image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PK }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
            docker pull ${{ secrets.ECR_URI }}:latest
            docker rm django --force || true
            docker run -d --network host --name django -e CLOUD=True ${{ secrets.ECR_URI }}:latest
  migrate:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance and run migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PK }}
          script: |
            docker exec django python manage.py migrate
  collectstatic:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance and collect static files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PK }}
          script: |
            docker exec django python manage.py collectstatic --noinput
